FROM python:3.7-slim

RUN apt update -y && \
    apt install -y python3-dev && \
    pip3 install --upgrade pip
WORKDIR /opt

COPY ./stinger .
COPY ./configs ./configs

RUN pip3.7 install --requirement ./requirements.txt --no-cache-dir
RUN pip3.7 install --requirement ./requirements-tests.txt --no-cache-dir

ENV PYTHONPATH=/opt:$PYTHONPATH
ENV CONFIG_PATH=/opt/configs/

RUN	coverage run -m pytest ./tests --disable-warnings
RUN	coverage xml -o coverage-report.xml
RUN	mutmut --paths-to-mutate ./src --tests-dir ./tests run || true
RUN	bandit -r ./ -x ./tests

EXPOSE 8080

ENTRYPOINT python3 ./run.py
